# Generated by Django 4.0.1 on 2022-01-14 06:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edinet_code', models.CharField(max_length=200, unique=True, verbose_name='EDINETコード')),
                ('sec_code', models.IntegerField(blank=True, null=True, unique=True, verbose_name='証券コード')),
                ('jcn', models.BigIntegerField(blank=True, null=True, verbose_name='法人番号')),
                ('corporation_type', models.CharField(default='内国法人・組合', max_length=30, verbose_name='法人の種別')),
                ('listing_type', models.BooleanField(null=True, verbose_name='上場区分')),
                ('linking_type', models.BooleanField(null=True, verbose_name='連結の有無')),
                ('capital', models.IntegerField(blank=True, default=0, verbose_name='資本金')),
                ('setting_day', models.DateField(null=True, verbose_name='決算日')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='所在地')),
                ('industry_type', models.CharField(blank=True, max_length=30, verbose_name='業種')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='法人名')),
                ('name_eng', models.CharField(blank=True, max_length=100, verbose_name='法人名(英字)')),
                ('name_kana', models.CharField(blank=True, max_length=100, verbose_name='法人名(ヨミ)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
